<a href="https://colab.research.google.com/github/theAkhileshRai/Projects/blob/master/Binary_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [0]:
df1 = pd.read_csv('/content/Combined_df.csv',index_col=False)

In [9]:
df1.head()

Unnamed: 0           time  cyl  ...  y_true  leak_level     station
0           0  05/04/19 2:30    1  ...       1           2  Cross Barr
1           1  05/04/19 3:30    1  ...       1           2  Cross Barr
2           2  05/04/19 4:30    1  ...       1           2  Cross Barr
3           3  05/04/19 5:30    1  ...       1           2  Cross Barr
4           4  05/04/19 6:30    1  ...       1           2  Cross Barr

[5 rows x 16 columns]

In [10]:
df1.columns

Index(['Unnamed: 0', 'time', 'cyl', 's_temp_crank', 'd_temp_crank',
       's_pressure_crank', 'd_pressure_crank', 'rpm_crank', 's_temp_mean',
       'd_temp_mean', 's_pressure_mean', 'd_pressure_mean', 'rpm_mean',
       'y_true', 'leak_level', 'station'],
      dtype='object')

In [0]:
df1 = df1.drop(columns='Unnamed: 0')
df1['y_true'] = df1['y_true'].fillna(0)
df1['leak_level'] = df1['leak_level'].fillna(0)

In [12]:
df1.head()

time  cyl  s_temp_crank  ...  y_true  leak_level     station
0  05/04/19 2:30    1      0.666534  ...       1           2  Cross Barr
1  05/04/19 3:30    1      0.716066  ...       1           2  Cross Barr
2  05/04/19 4:30    1      0.687551  ...       1           2  Cross Barr
3  05/04/19 5:30    1      0.686916  ...       1           2  Cross Barr
4  05/04/19 6:30    1      0.698125  ...       1           2  Cross Barr

[5 rows x 15 columns]

In [13]:
df1.columns

Index(['time', 'cyl', 's_temp_crank', 'd_temp_crank', 's_pressure_crank',
       'd_pressure_crank', 'rpm_crank', 's_temp_mean', 'd_temp_mean',
       's_pressure_mean', 'd_pressure_mean', 'rpm_mean', 'y_true',
       'leak_level', 'station'],
      dtype='object')

In [14]:
df1['leak_level'].unique()

array([2, 0, 3, 1, 4])

In [0]:
X = df1.iloc[:,1:12]

In [16]:
X

cyl  s_temp_crank  ...  d_pressure_mean   rpm_mean
0         1      0.666534  ...        10.142075  10.063987
1         1      0.716066  ...        10.053597  10.075669
2         1      0.687551  ...        10.001306  10.081478
3         1      0.686916  ...        10.008420  10.054274
4         1      0.698125  ...        10.009700  10.091478
...     ...           ...  ...              ...        ...
165856    4      0.728417  ...         2.375134  12.358284
165857    4      0.686059  ...         2.370367  12.359520
165858    4      0.663322  ...         2.373662  12.352143
165859    4      0.645405  ...         2.373709  12.353393
165860    4      0.637614  ...         2.378750  12.357672

[165861 rows x 11 columns]

In [0]:
y_true = df1.iloc[:,13]

In [19]:
y_true.unique()

array([2, 0, 3, 1, 4])

In [0]:
y_true=y_true.fillna(0)

In [21]:
y_true.unique()

array([2, 0, 3, 1, 4])

In [0]:
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(X, y_true, test_size=test_size)

In [0]:
from collections import Counter

In [24]:
print(X_train.shape,y_train.shape)

(111126, 11) (111126,)


In [25]:
Counter(y_train)

Counter({0: 91828, 1: 3345, 2: 8157, 3: 2641, 4: 5155})

In [26]:
X_test.shape

(54735, 11)

In [0]:
from sklearn.model_selection import GridSearchCV

In [0]:
# A parameter grid for XGBoost
params = {
        'min_child_weight': [5],
        'gamma': [0.5, 1, 1.5, 2, 5],
        #'subsample': [0.6, 0.8, 1.0],

        #'colsample_bytree': [0.6, 0.8, 1.0],
        'max_depth': [3]
        }

# Binary Classifier

In [0]:
binary_true = df1.iloc[:,12]

In [47]:
binary_true

0         1
1         1
2         1
3         1
4         1
         ..
165856    0
165857    0
165858    0
165859    0
165860    0
Name: y_true, Length: 165861, dtype: int64

In [0]:
binary_true=binary_true.fillna(0)

In [55]:
binary_true.unique()

array([1, 0])

In [0]:
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(X, binary_true, test_size=test_size)

In [57]:
binary_true.unique()

array([1, 0])

In [0]:
model = XGBClassifier(learning_rate=0.05,max_delta_step=1,n_estimators=200)


In [0]:
# A parameter grid for XGBoost
params = {
        'min_child_weight': [5],
        'gamma': [0.5, 1, 1.5, 2, 5],
        #'subsample': [0.6, 0.8, 1.0],

        #'colsample_bytree': [0.6, 0.8, 1.0],
        'max_depth': [3]
        }

In [0]:
model = XGBClassifier()
binary_clf = GridSearchCV(model, params)

In [61]:
binary_clf.fit(X_train, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='deprecated', n_jobs=None,
             param_grid={'gamma': [0.5, 1, 1.5, 2, 5], 'max_depth': [3],
                         'min_child_weight': [5]},
             pre_dispatch='2*n_jobs', refit=True, 

In [0]:
y_pred = binary_clf.predict(X_test)

In [0]:
binary_predictions = [round(value) for value in y_pred]

In [64]:
accuracy = accuracy_score(y_test, binary_predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 87.74%


In [66]:
from sklearn.metrics import multilabel_confusion_matrix
multilabel_confusion_matrix(y_test,binary_predictions,labels=[0,1])

array([[[ 3268,  6312],
        [  399, 44756]],

       [[44756,   399],
        [ 6312,  3268]]])

In [0]:
import pickle
filename = '/content/binary_finalized_model.pkl'
pickle.dump(binary_clf, open(filename, 'wb'))

In [68]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

0.8773910660454919


In [69]:
from sklearn.metrics import classification_report
print(classification_report(y_test, binary_predictions))

              precision    recall  f1-score   support

           0       0.88      0.99      0.93     45155
           1       0.89      0.34      0.49      9580

    accuracy                           0.88     54735
   macro avg       0.88      0.67      0.71     54735
weighted avg       0.88      0.88      0.85     54735

