<a href="https://colab.research.google.com/github/theAkhileshRai/Projects/blob/master/XGB_Multi_and_Binary_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [0]:
df1 = pd.read_csv('/content/Combined_df.csv',index_col=False)

In [0]:
df1.head()

Unnamed: 0           time  cyl  ...  y_true  leak_level     station
0           0  05/04/19 2:30    1  ...       1           2  Cross Barr
1           1  05/04/19 3:30    1  ...       1           2  Cross Barr
2           2  05/04/19 4:30    1  ...       1           2  Cross Barr
3           3  05/04/19 5:30    1  ...       1           2  Cross Barr
4           4  05/04/19 6:30    1  ...       1           2  Cross Barr

[5 rows x 16 columns]

In [0]:
df1.columns

Index(['Unnamed: 0', 'time', 'cyl', 's_temp_crank', 'd_temp_crank',
       's_pressure_crank', 'd_pressure_crank', 'rpm_crank', 's_temp_mean',
       'd_temp_mean', 's_pressure_mean', 'd_pressure_mean', 'rpm_mean',
       'y_true', 'leak_level', 'station'],
      dtype='object')

In [0]:
df1 = df1.drop(columns='Unnamed: 0')

In [0]:
df1.head()

time  cyl  s_temp_crank  ...  y_true  leak_level     station
0  05/04/19 2:30    1      0.666534  ...       1           2  Cross Barr
1  05/04/19 3:30    1      0.716066  ...       1           2  Cross Barr
2  05/04/19 4:30    1      0.687551  ...       1           2  Cross Barr
3  05/04/19 5:30    1      0.686916  ...       1           2  Cross Barr
4  05/04/19 6:30    1      0.698125  ...       1           2  Cross Barr

[5 rows x 15 columns]

In [0]:
df1.columns

Index(['time', 'cyl', 's_temp_crank', 'd_temp_crank', 's_pressure_crank',
       'd_pressure_crank', 'rpm_crank', 's_temp_mean', 'd_temp_mean',
       's_pressure_mean', 'd_pressure_mean', 'rpm_mean', 'y_true',
       'leak_level', 'station'],
      dtype='object')

In [0]:
df1['leak_level'].unique()

array([2, 0, 3, 1, 4])

In [0]:
X = df1.iloc[:,1:12]

In [0]:
X

cyl  s_temp_crank  ...  d_pressure_mean   rpm_mean
0         1      0.666534  ...        10.142075  10.063987
1         1      0.716066  ...        10.053597  10.075669
2         1      0.687551  ...        10.001306  10.081478
3         1      0.686916  ...        10.008420  10.054274
4         1      0.698125  ...        10.009700  10.091478
...     ...           ...  ...              ...        ...
165856    4      0.728417  ...         2.375134  12.358284
165857    4      0.686059  ...         2.370367  12.359520
165858    4      0.663322  ...         2.373662  12.352143
165859    4      0.645405  ...         2.373709  12.353393
165860    4      0.637614  ...         2.378750  12.357672

[165861 rows x 11 columns]

In [0]:
y_true = df1.iloc[:,13]

In [0]:
y_true.unique()

array([2, 0, 3, 1, 4])

In [0]:
y_true=y_true.fillna(0)

In [0]:
y_true.unique()

array([2, 0, 3, 1, 4])

In [0]:
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(X, y_true, test_size=test_size)

In [0]:
from collections import Counter

In [0]:
print(X_train.shape,y_train.shape)

(111126, 11) (111126,)


In [0]:
Counter(y_train)

Counter({0: 91720, 1: 3379, 2: 8234, 3: 2631, 4: 5162})

In [0]:
X_test.shape

In [0]:
from sklearn.model_selection import GridSearchCV

In [0]:
# A parameter grid for XGBoost
params = {
        'min_child_weight': [5],
        'gamma': [0.5, 1, 1.5, 2, 5],
        #'subsample': [0.6, 0.8, 1.0],

        #'colsample_bytree': [0.6, 0.8, 1.0],
        'max_depth': [3,4,5]
        }

In [0]:
model = XGBClassifier()
clf = GridSearchCV(model, params)

In [0]:
clf

GridSearchCV(cv=None, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='deprecated', n_jobs=None,
             param_grid={'gamma': [0.5, 1, 1.5, 2, 5], 'max_depth': [3, 4, 5],
                         'min_child_weight': [5]},
             pre_dispatch='2*n_jobs', refit=

In [0]:
clf.fit(X_train, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='deprecated', n_jobs=None,
             param_grid={'gamma': [0.5, 1, 1.5, 2, 5], 'max_depth': [3, 4, 5],
                         'min_child_weight': [5]},
             pre_dispatch='2*n_jobs', refit=

In [0]:
X_test

cyl  s_temp_crank  ...  d_pressure_mean   rpm_mean
62070     3      0.147850  ...         0.362104   1.905186
55277     1      0.116526  ...         0.372009   1.904313
163798    4      0.409747  ...         2.406751  12.232851
141982    3      0.684986  ...         0.196529  11.553271
102416    2      0.486919  ...        10.468251   8.667481
...     ...           ...  ...              ...        ...
112612    4      0.091605  ...         0.305020   2.231318
149341    4      0.500966  ...         2.138505  11.556502
1236      1      0.575471  ...         9.963310  10.175806
134326    2      0.536042  ...         8.323240  11.557682
77140     4      0.069402  ...         1.028917   1.823634

[54735 rows x 11 columns]

In [0]:
y_pred = clf.predict(X_test)

In [0]:
predictions = [round(value) for value in y_pred]

In [0]:
from collections import Counter
Counter(predictions)

Counter({0: 48071, 1: 798, 2: 2977, 3: 995, 4: 1894})

In [0]:
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 92.46%


In [0]:
from sklearn.metrics import multilabel_confusion_matrix

In [0]:
multilabel_confusion_matrix(y_test,predictions,labels=[0,1,2,3,4])

array([[[ 6071,  3300],
        [  593, 44771]],

       [[52987,   163],
        [  950,   635]],

       [[50639,   194],
        [ 1119,  2783]],

       [[53286,   107],
        [  454,   888]],

       [[51830,   363],
        [ 1011,  1531]]])

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96     45364
           1       0.80      0.40      0.53      1585
           2       0.93      0.71      0.81      3902
           3       0.89      0.66      0.76      1342
           4       0.81      0.60      0.69      2542

    accuracy                           0.92     54735
   macro avg       0.87      0.67      0.75     54735
weighted avg       0.92      0.92      0.92     54735



In [0]:
import pickle
filename = '/content/best_model_2.pkl'


In [0]:
pickle.dump(clf, open(filename, 'wb'))

In [0]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

0.9246003471270667


In [0]:
clf.cv_results_

{'mean_fit_time': array([36.44264412, 48.54719915, 61.23280549, 36.57319245, 48.63273411,
        61.08445234, 36.70845151, 48.52082572, 61.19560924, 36.82089319,
        48.48151999, 60.94255633, 36.55998268, 48.49838948, 61.10313129]),
 'mean_score_time': array([0.35640011, 0.46006541, 0.55730696, 0.3607183 , 0.45909815,
        0.5566319 , 0.36185174, 0.45540409, 0.55527725, 0.36321158,
        0.4540235 , 0.55405622, 0.36747108, 0.4533    , 0.54009151]),
 'mean_test_score': array([0.88439253, 0.90442378, 0.92143152, 0.88607524, 0.90507171,
        0.92132354, 0.88458148, 0.90479274, 0.92095459, 0.88523839,
        0.90469375, 0.92076561, 0.88438349, 0.90346092, 0.92036967]),
 'param_gamma': masked_array(data=[0.5, 0.5, 0.5, 1, 1, 1, 1.5, 1.5, 1.5, 2, 2, 2, 5, 5,
                    5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 

In [0]:
clf.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0.5,
              learning_rate=0.1, max_delta_step=0, max_depth=5,
              min_child_weight=5, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)